/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import Client.ClientConnection;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Kasper
 */
public class GUI extends javax.swing.JFrame implements Observer{

    ClientConnection cc;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        addWindowListener(new WindowAdapter(){
        @Override
        public void windowClosing(WindowEvent e){
            if (cc != null){
                cc.close();
            }
        }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewSwitch = new javax.swing.JPanel();
        authPanel = new javax.swing.JPanel();
        authButton = new javax.swing.JButton();
        responsePanel = new javax.swing.JPanel();
        labelResponse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        viewSwitch.setLayout(new java.awt.CardLayout());

        authPanel.setLayout(new java.awt.GridBagLayout());

        authButton.setText("jButton1");
        authButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authButtonActionPerformed(evt);
            }
        });
        authPanel.add(authButton, new java.awt.GridBagConstraints());

        viewSwitch.add(authPanel, "authPanel");

        labelResponse.setText("jLabel1");

        javax.swing.GroupLayout responsePanelLayout = new javax.swing.GroupLayout(responsePanel);
        responsePanel.setLayout(responsePanelLayout);
        responsePanelLayout.setHorizontalGroup(
            responsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, responsePanelLayout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(labelResponse)
                .addGap(325, 325, 325))
        );
        responsePanelLayout.setVerticalGroup(
            responsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(responsePanelLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(labelResponse)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        viewSwitch.add(responsePanel, "responsePanel");

        getContentPane().add(viewSwitch);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authButtonActionPerformed

        this.cc = new ClientConnection("localhost", 9090);
        this.cc.addObserver(this);
        Thread thread1 = new Thread(this.cc);
        thread1.start();
        
        CardLayout layout = (CardLayout) this.viewSwitch.getLayout();
        layout.show(this.viewSwitch, "responsePanel");
        
        
    }//GEN-LAST:event_authButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authButton;
    private javax.swing.JPanel authPanel;
    private javax.swing.JLabel labelResponse;
    private javax.swing.JPanel responsePanel;
    private javax.swing.JPanel viewSwitch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if(o.getClass().equals(ClientConnection.class)){
            String response = (String) arg;
            labelResponse.setText(labelResponse.getText() + "\n" + response);
        }
    }
}
